# Generated by Django 4.2 on 2023-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sync', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sync',
            },
        ),
    ]
