# Generated by Django 4.2 on 2023-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sync',
            options={'managed': False},
        ),
    ]
